<section class="main_body">
	<header>
		<h2>Forum dyskusyjne</h2>
	</header>
	<div class="content">
		<?php if ($boards = $this->board->fetchAll()): ?>
		<?php foreach ($boards as $board): ?>
		<table id="forum">
			<thead>
				<tr>
					<th class="column-left"><?php echo $board['title']; ?></th>
					<th>Tematów</th>
					<th>Wpisów</th>
					<th>Ostatni wpis</th>
				</tr>
			</thead>
			<?php if ($categories = $this->category->fetchAll($board['id'])): ?>
			<tbody>
				<?php foreach ($categories as $category): ?>
				<tr>
					<td>
						<a href="#" class="column-title"><?php echo $category['title']; ?></a>
						<p><?php echo $category['description']; ?></p>
					</td>
					<td>0</td>
					<td>0</td>
					<td>Brak</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		<?php endforeach; ?>
		<?php endif; ?>
	</div>
</section>