<ul class="breadcrumbs">
	<li><a href="<?php echo $this->router->path(array('module' => 'forum')); ?>"><?php echo __('Forum'); ?></a></li>
	<li><a href="<?php echo $this->router->path(array('module' => 'forum')); ?>#board-<?php echo $category['board_id']; ?>"><?php echo $category['board']; ?></a></li>
	<li><strong><?php echo $category['title']; ?></strong></li>
</ul>
<?php opentable(__('Forum')); ?>
		<table class="forum">
			<thead>
				<tr>
					<th class="col-6 align-left">Tytuł wątku</th>
					<th class="col-2">Autor</th>
					<th class="col-1">Odpowiedzi</th>
					<th class="col-3">Ostatni wpis</th>
				</tr>
			</thead>
			<tbody>
				<?php if ($threads): ?>
				<?php foreach ($threads as $thread): ?>
				<tr>
					<td>
						<a href="#" class="text-title"><?php echo $thread['title']; ?></a>
					</td>
					<td class="align-center"><?php echo HELP::profileLink($thread['username'], $thread['user_id']); ?></td>
					<td class="align-center"><?php echo $thread['entries']; ?></td>
					<td>-</td>
				</tr>
				<?php endforeach; ?>
				<?php else: ?>
				<tr>
					<td colspan="4">W tej kategorii nie został utworzony żaden wątek.</td>
				</tr>
				<?php endif; ?>
			</tbody>
		</table>
<?php closetable(); ?>