<?php opentable(__('Forum')); ?>
		<?php if ($boards = $board->fetchAll()): ?>
		<?php foreach ($boards as $board): ?>
		<table id="forum">
			<thead>
				<tr>
					<th class="column-left"><?php echo $board['title']; ?></th>
					<th><?php echo __('Threads'); ?></th>
					<th><?php echo __('Entries'); ?></th>
					<th><?php echo __('Last entry'); ?></th>
				</tr>
			</thead>
			<?php if ($categories = $category->fetchAll($board['id'])): ?>
			<tbody>
				<?php foreach ($categories as $category): ?>
				<tr>
					<td>
						<a href="<?php echo $this->router->path(array('module' => 'forum', 'controller' => 'category', $category['id'])); ?>" class="column-title"><?php echo $category['title']; ?></a>
						<p><?php echo $category['description']; ?></p>
					</td>
					<td>0</td>
					<td>0</td>
					<td>Brak</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		<?php endforeach; ?>
		<?php endif; ?>
<?php closetable(); ?>